version: '3'
services:
    api:
        build: ./server
        ports:
            - '8080:8080'
        container_name: app-server
    client:
        build: ./front
        ports:
            - '80:80'
        container_name: app-ui
